apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
type: Opaque
stringData:
  SLACK_CHANNEL: {{ required "A Slack channel is required!" .Values.notifier.slack.channel }}
  SLACK_TOKEN: {{ required "A Slack token is required!" .Values.notifier.slack.token }}